import type { Metadata } from "next";
import "./globals.css";
import {fraunces} from './fonts';

export const metadata: Metadata = {
  title: "koi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fraunces.className}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
