import type { Metadata } from "next";
import "@/styles/globals.css";
import { fraunces } from '../lib/fonts';
import { VolumeProvider } from "@/lib/context/volume-context";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import { cn } from "@/utils";
import { bgPrimary } from "@/components";

export const metadata: Metadata = {
  title: "koi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fraunces.className} !p-0`}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="preload" href="/images/circle-bars-palep-p.webp" as="image" />
      </head>
      <VolumeProvider>
        <body>
          {children}
          <SpeedInsights />
          <Analytics />
          <div id="page-transition-overlay" className="min-w-screen min-h-screen flex items-center justify-center relative opacity-0 pointer-events-none">
            {bgPrimary()}
            <div className="flex flex-col items-center justify-center gap-8">
              <div className="min-h-[180px] flex flex-col items-center justify-center gap-4">
                <span className="eyes"></span>
                <span className="spinner"></span>
              </div>
              <div>
                <div
                  className={cn(
                    "loading loading04",
                    "text-4xl lg:text-8xl font-extrabold tracking-wider",
                  )}
                >
                  <span>L</span>
                  <span>O</span>
                  <span>A</span>
                  <span>D</span>
                  <span>I</span>
                  <span>N</span>
                  <span>G</span>
                </div>
              </div>
            </div>
          </div>
        </body>
      </VolumeProvider>
    </html>
  );
}
